# Generated by Django 4.1.4 on 2022-12-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment", old_name="date", new_name="appointment_date",
        ),
    ]
